version: '3.8'

services:
  ffc-sfi-api-gateway:
    build:
      context: .
      target: production
    image: ffc-sfi-api-gateway
    container_name: ffc-sfi-api-gateway
    environment: 
      APPINSIGHTS_CLOUDROLE: ffc-sfi-crown-hosting-prototype
      APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY}
      USE_MOCK: ${USE_MOCK}
      CH_API: ${CH_API}
      CH_API_ID: ${CH_API_ID}
      CH_API_KEY: ${CH_API_KEY}
