{{- include "ffc-helm-library.container-secret" (list . "ffc-sfi-api-gateway.container-secret") -}}
{{- define "ffc-sfi-api-gateway.container-secret" -}}
stringData:
  {{- if .Values.appInsights.key }}
  APPINSIGHTS_INSTRUMENTATIONKEY: {{ quote .Values.appInsights.key }}
  {{- end }}
  CH_API_KEY: {{ quote .Values.container.chApiKey }}
{{- end -}}