environment: development
name: ffc-sfi-api-gateway
namespace: ffc-sfi
workstream: ffc-sfi
image: ffc-sfi-api-gateway

labels: {}

appInsights:
  key:

containerConfigMap:
  name: ffc-sfi-api-gateway-config-map

containerSecret:
  name: ffc-sfi-api-gateway-container-secret
  type: Opaque

service:
  port: 80
  type: ClusterIP

deployment:
  restartPolicy: Always
  priorityClassName: high
  replicas: 1
  minReplicas: 2
  maxReplicas: 4
  cpuThreshold: 80
  memoryThreshold: 80
  minReadySeconds: 0

container:
  imagePullPolicy: Always
  requestMemory: 80Mi
  requestCpu: 80m
  limitMemory: 120Mi
  limitCpu: 120m
  port: 3005
  useMock: false
  chApi:
  chApiId:
  chApiKey:

ingress:
  class: nginx
  endpoint: ffc-sfi-api-gateway
  server: example.com

livenessProbe:
  path: /healthz
  port: 3005
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  path: /healthy
  port: 3005
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3
